config/routes.rb
Geriatrics::Application.routes.draw do
  devise_for :users

  get "providers/attorney_insurance_providers"

  get "providers/financial_providers"

  get "providers/healthcare_providers"

  get "providers/caregiver_providers"

 get "providers/attorney_Insurance"

  resources :personal_properties

  resources :legal_doucuments

  resources :insurances

  resources :loans_credit_cards

  resources :banking_financials

  resources :medical_histories

  resources :medications

  resources :clients

  get "post/home"

  get "post/Geriatric_Care_Manager"

  get "post/Geriatric_Client"

  get "post/Providers"

  get "post/Medical_History"

  get "post/Banking_And_Financial"

  get "post/Other_Documents"

  

  

 
end

app/models/legal_doucument.rb
class LegalDoucument < ActiveRecord::Base
  attr_accessible :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
 validates_presence_of :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
end

app/controllers/legal_doucuments_controller.rb
class LegalDoucumentsController < ApplicationController
  # GET /legal_doucuments
  # GET /legal_doucuments.json
  def index
    @legal_doucuments = LegalDoucument.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @legal_doucuments }
    end
  end

  # GET /legal_doucuments/1
  # GET /legal_doucuments/1.json
  def show
    @legal_doucument = LegalDoucument.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @legal_doucument }
    end
  end

  # GET /legal_doucuments/new
  # GET /legal_doucuments/new.json
  def new
    @legal_doucument = LegalDoucument.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @legal_doucument }
    end
  end

  # GET /legal_doucuments/1/edit
  def edit
    @legal_doucument = LegalDoucument.find(params[:id])
  end

  # POST /legal_doucuments
  # POST /legal_doucuments.json
  def create
    @legal_doucument = LegalDoucument.new(params[:legal_doucument])

    respond_to do |format|
      if @legal_doucument.save
        format.html { redirect_to @legal_doucument, notice: 'Legal doucument was successfully created.' }
        format.json { render json: @legal_doucument, status: :created, location: @legal_doucument }
      else
        format.html { render action: "new" }
        format.json { render json: @legal_doucument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /legal_doucuments/1
  # PUT /legal_doucuments/1.json
  def update
    @legal_doucument = LegalDoucument.find(params[:id])

    respond_to do |format|
      if @legal_doucument.update_attributes(params[:legal_doucument])
        format.html { redirect_to @legal_doucument, notice: 'Legal doucument was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @legal_doucument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_doucuments/1
  # DELETE /legal_doucuments/1.json
  def destroy
    @legal_doucument = LegalDoucument.find(params[:id])
    @legal_doucument.destroy

    respond_to do |format|
      format.html { redirect_to legal_doucuments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/legal_doucuments_helper.rb
module LegalDoucumentsHelper
end

app/views/legal_doucuments/_form.html.erb
<%= form_for(@legal_doucument) do |f| %>
  <% if @legal_doucument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@legal_doucument.errors.count, "error") %> prohibited this legal_doucument from being saved:</h2>

      <ul>
      <% @legal_doucument.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :do_Not_Resuscitate %><br />
    <%= f.text_field :do_Not_Resuscitate %>
  </div>
  <div class="field">
    <%= f.label :healthcare_Directive %><br />
    <%= f.text_field :healthcare_Directive %>
  </div>
  <div class="field">
    <%= f.label :power_of_Attorney %><br />
    <%= f.text_field :power_of_Attorney %>
  </div>
  <div class="field">
    <%= f.label :will %><br />
    <%= f.text_area :will %>
  </div>
  <div class="field">
    <%= f.label :trust %><br />
    <%= f.text_field :trust %>
  </div>
  <div class="field">
    <%= f.label :wishes %><br />
    <%= f.text_area :wishes %>
  </div>
  <div class="field">
    <%= f.label :letter_of_Authorization %><br />
    <%= f.text_area :letter_of_Authorization %>
  </div>
  <div class="field">
    <%= f.label :pension_Papers %><br />
    <%= f.text_area :pension_Papers %>
  </div>
  <div class="field">
    <%= f.label :location_of_Original %><br />
    <%= f.text_field :location_of_Original %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/legal_doucuments/edit.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  <nav>
<h1>Editing legal_doucument</h1>

<%= render 'form' %>

<%= link_to 'Show', @legal_doucument %> |
<%= link_to 'Back', legal_doucuments_path %>

app/views/legal_doucuments/index.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  <nav>
<h1>Listing legal_doucuments</h1>

<table>
  <tr>
    <th>Do not resuscitate</th>
    <th>Healthcare directive</th>
    <th>Power of attorney</th>
    <th>Will</th>
    <th>Trust</th>
    <th>Wishes</th>
    <th>Letter of authorization</th>
    <th>Pension papers</th>
    <th>Location of original</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @legal_doucuments.each do |legal_doucument| %>
  <tr>
    <td><%= legal_doucument.do_Not_Resuscitate %></td>
    <td><%= legal_doucument.healthcare_Directive %></td>
    <td><%= legal_doucument.power_of_Attorney %></td>
    <td><%= legal_doucument.will %></td>
    <td><%= legal_doucument.trust %></td>
    <td><%= legal_doucument.wishes %></td>
    <td><%= legal_doucument.letter_of_Authorization %></td>
    <td><%= legal_doucument.pension_Papers %></td>
    <td><%= legal_doucument.location_of_Original %></td>
    <td><%= link_to 'Show', legal_doucument %></td>
    <td><%= link_to 'Edit', edit_legal_doucument_path(legal_doucument) %></td>
    <td><%= link_to 'Destroy', legal_doucument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Legal doucument', new_legal_doucument_path %>

app/views/legal_doucuments/new.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  <nav>
<h1>New legal_doucument</h1>

<%= render 'form' %>

<%= link_to 'Back', legal_doucuments_path %>

app/views/legal_doucuments/show.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  <nav>
<p id="notice"><%= notice %></p>

<p>
  <b>Do not resuscitate:</b>
  <%= @legal_doucument.do_Not_Resuscitate %>
</p>

<p>
  <b>Healthcare directive:</b>
  <%= @legal_doucument.healthcare_Directive %>
</p>

<p>
  <b>Power of attorney:</b>
  <%= @legal_doucument.power_of_Attorney %>
</p>

<p>
  <b>Will:</b>
  <%= @legal_doucument.will %>
</p>

<p>
  <b>Trust:</b>
  <%= @legal_doucument.trust %>
</p>

<p>
  <b>Wishes:</b>
  <%= @legal_doucument.wishes %>
</p>

<p>
  <b>Letter of authorization:</b>
  <%= @legal_doucument.letter_of_Authorization %>
</p>

<p>
  <b>Pension papers:</b>
  <%= @legal_doucument.pension_Papers %>
</p>

<p>
  <b>Location of original:</b>
  <%= @legal_doucument.location_of_Original %>
</p>


<%= link_to 'Edit', edit_legal_doucument_path(@legal_doucument) %> |
<%= link_to 'Back', legal_doucuments_path %>